### ISSUE TITLE
PR: set TE sensor offset

### ISSUE THREAD

**Issue by kalaws** [qix67/comfortzone_heatpump#3]
Could not post a PR, so I’m posting as an issue. 

Request is to be able to set the offset of a TE sensor. The use case is to adjust outside temperature upwards temporarily when electricity price is high, or weather forecast suggests sun will be warming house in the immediate future.

**Comment by qix67** [comment]
Do you know a way to do this using heatpump control panel ?

**Comment by kalaws** [comment]
Yes, in advanced settings this is possible for a whole range of TE sensors, at least in my firmware. I can confirm where, exactly, a little later this afternoon. 

Edit: I mean in the advanced service menu accessed by holding button for 6 seconds.

**Comment by qix67** [comment]
Ok. On my control panel, I can adjust TE0-TE7 and TE24.

I will take a look tomorrow to see what command the control panel send.

**Comment by kalaws** [comment]
Outside temperature is TE0, and correction can be up to + / - 10 C.

**Comment by kalaws** [comment]
Perhaps a better solution is to adjust input temp at the various outside temps (ie 10, 5, 0, -5, -10, -15)?

**Comment by qix67** [comment]
I just push a new version of the library. A new function is added: set_sensor_offset.

Hopefully, most of the code was already in the library, it is a minor change.

I have compiled it without error but I have not tested it because I currently have no webserver to perform OTA update of my ESP8266.

**Comment by kalaws** [comment]
wow, great work!
